// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbySRQwKXtRFhMdbY0Fge-WLLtfo4glE',
    appId: '1:416750064259:web:0e342c898d9169790281b6',
    messagingSenderId: '416750064259',
    projectId: 'crypto-coin-a8d6d',
    authDomain: 'crypto-coin-a8d6d.firebaseapp.com',
    storageBucket: 'crypto-coin-a8d6d.firebasestorage.app',
    measurementId: 'G-TNS9KS0WGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHatmIV-JE8Ocd638WZaLZ0Bx6PMsFQbU',
    appId: '1:416750064259:android:85bafcbe8c24ab8d0281b6',
    messagingSenderId: '416750064259',
    projectId: 'crypto-coin-a8d6d',
    storageBucket: 'crypto-coin-a8d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ_GN3lk9ja9wzPZpEtmD8zJY6OG4Vpd4',
    appId: '1:416750064259:ios:4814041ea1b999350281b6',
    messagingSenderId: '416750064259',
    projectId: 'crypto-coin-a8d6d',
    storageBucket: 'crypto-coin-a8d6d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ_GN3lk9ja9wzPZpEtmD8zJY6OG4Vpd4',
    appId: '1:416750064259:ios:4814041ea1b999350281b6',
    messagingSenderId: '416750064259',
    projectId: 'crypto-coin-a8d6d',
    storageBucket: 'crypto-coin-a8d6d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjbySRQwKXtRFhMdbY0Fge-WLLtfo4glE',
    appId: '1:416750064259:web:ca5a440707b03a710281b6',
    messagingSenderId: '416750064259',
    projectId: 'crypto-coin-a8d6d',
    authDomain: 'crypto-coin-a8d6d.firebaseapp.com',
    storageBucket: 'crypto-coin-a8d6d.firebasestorage.app',
    measurementId: 'G-P6NCSB5S0P',
  );
}
